---
stages:
  - lint
  - build
  - unit_test
  - int_deploy
  - int_test

variables:
  GL_KETCHUP_NAME: ketchup
  GL_KETCHUP_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${GL_KETCHUP_NAME}
  GL_KETCHUP_NGINX_NAME: ketchup_nginx
  GL_KETCHUP_NGINX_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}/${GL_KETCHUP_NGINX_NAME}

before_script:
  - export BUILD_TAG="devel-$(echo $CI_COMMIT_SHA | cut -c1-8)"

Lint_Check:
  stage: lint
  image:
    name: hadolint/hadolint
  script:
    - hadolint --ignore="SC2086" - < ./flexible_artifacts/${GL_KETCHUP_NAME}/Dockerfile
    - hadolint - < ./flexible_artifacts/${GL_KETCHUP_NGINX_NAME}/Dockerfile
  tags:
    - docker

Build_Ketchup_Image:
  stage: build
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build --force-rm=true -f ./flexible_artifacts/${GL_KETCHUP_NAME}/Dockerfile -t ${GL_KETCHUP_IMAGE}:${BUILD_TAG} .
    - docker push ${GL_KETCHUP_IMAGE}
  tags:
    - docker

Build_Ketchup_Nginx_Image:
  stage: build
  image: docker:stable
  script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build --force-rm=true -f ./flexible_artifacts/${GL_KETCHUP_NGINX_NAME}/Dockerfile -t ${GL_KETCHUP_NGINX_IMAGE}:${BUILD_TAG} .
    - docker push ${GL_KETCHUP_NGINX_IMAGE}
  tags:
    - docker

Unit_Test_Ketchup:
  stage: unit_test
  image:
    name: irixjp/lint-rules:latest
    entrypoint: [""]
  script:
    - cd ./flexible_artifacts/
    - ansible-playbook -i ./hosts/ketchup/inventory -t develop -e "KETCHUP_IMAGE=${GL_KETCHUP_IMAGE}" -e "KETCHUP_NGINX_IMAGE=${GL_KETCHUP_NGINX_IMAGE}" -e "IMAGE_VER=${BUILD_TAG}" ./manage_ketchup_app.yml -vv
    - cd ../tests/
    - ansible-playbook -e 'artifact=containered' -e "ansible_become=false" -e "ansible_connection=docker" -i ../flexible_artifacts/hosts/docker.py -i ../flexible_artifacts/hosts/ketchup/inventory ./ketchup_test.yml -vv
    - ansible-playbook -e 'artifact=containered' -e "ansible_become=false" -e "ansible_connection=docker" -i ../flexible_artifacts/hosts/docker.py -i ../flexible_artifacts/hosts/ketchup/inventory ./ketchup_nginx_test.yml -vv
  after_script:
    - cd ./flexible_artifacts/
    - ansible-playbook -i ./hosts/ketchup/inventory -t absent ./manage_ketchup_app.yml -vv
  tags:
    - docker

Init_Deploy_Kethup:
  stage: int_deploy
  image:
    name: irixjp/lint-rules:latest
    entrypoint: [""]
  script:
    - cd ./flexible_artifacts/
    - ansible-playbook -i ./hosts/ketchup/inventory -t develop -e "KETCHUP_IMAGE=${GL_KETCHUP_IMAGE}" -e "KETCHUP_NGINX_IMAGE=${GL_KETCHUP_NGINX_IMAGE}" -e "IMAGE_VER=${BUILD_TAG}" ./manage_ketchup_app.yml -vv
  after_script:
    - sleep 10
  tags:
    - docker

Init_Test_Kethup:
  stage: int_test
  image:
    name: irixjp/lint-rules:latest
    entrypoint: [""]
  script:
    - cd ./tests/
    - ansible-playbook -i ../flexible_artifacts/hosts/ketchup/inventory -e "ketchup_nginx_host=192.168.33.11" ./int_test_ketchup_nginx.yml -vv
  tags:
    - docker
