---
- name: Cleanup Ketchup host
  hosts: "ketchup"
  gather_facts: True

  roles:
    - role: cleanup_ketchup


- name: Cleanup Ngnix frontend for Ketchup
  hosts: "ketchup_nginx"
  roles:
    - role: cleanup_nginx
